name: Documentation
on:
  push:
    branches:
      - main
    tags: "*"
jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    env:
      PYTHON: "" # Force using Conda in PyCall (required for DFTK on ubuntu)
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: "1.7"
      - name: add CESMIX registry
        run: |
          julia -e '
            using Pkg
            Pkg.Registry.add("General")
            Pkg.Registry.add(RegistrySpec(url = "https://github.com/cesmix-mit/CESMIX.git"))
          '
        shell: bash
      - name: instantiate docs
        run: |
          julia --project=docs -e '
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()
          '
      - name: run doctests
        run: |
          julia --project=docs -e '
            using Documenter: DocMeta, doctest
            using Atomistic
            DocMeta.setdocmeta!(Atomistic, :DocTestSetup, :(using Atomistic); recursive=true)
            doctest(Atomistic)
          '
      - name: generate docs
        run: julia --project=docs docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
