name: Documentation

on:
  pull_request:
  push:
    branches:
      - main
    tags: "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: "1"
      - run: |
          julia --project -e '
            using Pkg
            Pkg.Registry.add("https://github.com/cesmix-mit/CESMIX.git")
          '
      - run: |
          julia --project -e '
            using Pkg
            Pkg.instantiate()
            Pkg.precompile()
          '
      - run: |
          julia --project=docs -e '
            using Pkg
            # Until all dependencies are registered
            # Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()'
      - run: |
          julia --project=docs -e '
            using Documenter: DocMeta, doctest
            using Atomistic
            DocMeta.setdocmeta!(Atomistic, :DocTestSetup, :(using Atomistic); recursive=true)
            doctest(Atomistic)'
      - run: julia --project=docs docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
